name: Discord Webhook Notification

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Send Discord Webhook
        env:
          DISCORD_WEBHOOK: 'https://l.webhook.party/hook/mmKwAxyAqVOgZ7uo%2BuNVdP1uIszqz%2FULHbRSpKG4nsSwwFfduRgwF2GRAw3ddjrnw7J95%2FMvW8XuQLQg4grEFBxs%2FPf10kbVTmaZ81bxHdp%2FQaByNj6xxWtAG269kA%2BdA3YZqtw2KW%2Fht189AJmU1sbZDmOX0BkcFIMLZEZYqnQM9jAq%2FGPwKzEuAkK7o9AK3688mjA2oSVUG84qo97Mzhl9FKF4x19wjq8quw0b95s7wjaYb6TANCNlCEhHaLGdqeLNCUCWjgwxAbHr7tQ1gOBUlh%2BpMhqU0BxvjDjAVJjGL5PaCnfYdsVlao3g4j6%2Bp99W%2F%2Bnp4cydznn1e0psL6kcT11HMXMYCCPIL%2BA%2Bpywvxxi43PrPq2LqEH444d0xKKfYW1y9Phk%3D/olnBBxGbNS58v5Pk'
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: node .github/scripts/discordNotify.js
