name: Discord Webhook Notification

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Send Discord Webhook
        env:
          DISCORD_WEBHOOK: 'https://l.webhook.party/hook/HM2kDFQM7%2Bujf8YMzZ%2F8eonj3%2FVff4RVr72pnjasfgYUn3ZoNXK54gg1NpEzV0JiZRvmTceMptPJgqVngnIGAW65953wUe6L5DpsIPjrPe3KwTdA6yy8VQc7gVCjXRjr58pdMnYKMYcOkAGByMvtJ%2Bz5XTMm1vUS9NIfQUf1l5YDRX8qiu7nd2go9xTDySmc%2BqDvmemy8nPzZJZHeoJw2UGww9WbSR8PWnMHs9khiq8cHqCBW%2BMukuYf9BO6wjz1U3dl1fhTJQOwbempj%2FX8uYiqZjd2s4Pf%2FIpwT8wRbEa8ktEeMYEh2%2BcbemYbgdL%2FFh1jAiWLSLtc1PqRW3h2LyQM1fkbbbWMtlaCkvJULxJlzCzo6BmoNbinfi%2Fo93sbG9gfdVfeB70%3D/XKkSO6MJT3BXtpiH'
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: node .github/scripts/discordNotify.js
